name: Release

on:
  push:
    tags:
    - '*'

jobs:
  test-using-java:
    strategy:
      matrix:
        java-version: [ '8', '11', '17', '21' ]
    name: Test using Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Print java version
      run: java -version

    - name: Install dependencies
      run: lein deps

    - name: Run clj tests
      run: lein test

    - name: Run midje tests
      run: lein midje

  release:
    name: 'Publish on Clojars'
    runs-on: ubuntu-latest
    needs: test-using-java
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: lein deps

    - name: Publish on Clojars
      run: lein deploy publish
      env:
          CLOJARS_USERNAME: eng-prod-nubank
          CLOJARS_PASSWD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
